site_name: gcxmlib
site_url:
site_author: Ryou Ohsawa
site_description: >-
  A cross-matching library with great circle.

repo_name: ryou_ohsawa/gcxmlib
repo_url: https://bitbucket.org/ryou_ohsawa/gcxmlib/src/master/
edit_uri: ""

copyright: Copyright &copy; 2021&ndash; Ryou Ohsawa

theme:
  name: 'material'
  icon:
    logo: logo
  language: 'en'
  palette:
    scheme: default
    primary: blue grey
    accent: deep orange
  features:
    - navigation.indexes
    - header.autohide

extra_css:
  - css/local.css
extra_javascript:
  - js/config_mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - toc:
      toc_depth: 3
  - extra
  - admonition
  - smarty
  - sane_lists
  - meta
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: True
  - pymdownx.arithmatex:
      generic: true

nav:
  - Top Page: index.md
  - Python Reference:
    - Getting Started: python/index.md
    - direction_cosine: python/direction_cosine.md
    - footprint: python/footprint.md
    - trail: python/trail.md
    - trajectory: python/trajectory.md
    - Index: python/index_table.md
  - C++ Reference:
    - Getting Started: cpp/index.md
    - constants: cpp/constants.md
    - angle: cpp/angle.md
    - vector3: cpp/vector3.md
    - matrix3: cpp/matrix3.md
    - direction_cosine: cpp/direction_cosine.md
    - footprint: cpp/footprint.md
    - great_circle: cpp/great_circle.md
    - minor_arc: cpp/minor_arc.md
    - trail: cpp/trail.md
    - trajectory: cpp/trajectory.md
    - functions: cpp/functions.md
    - Index: cpp/index_table.md
    - Source code: cpp/source.md
  - bitbucket: https:://bitbucket.org/ryou_ohsawa/gcxmlib/src/master/
  - PyPi: https://pypi.org/project/gcxmlib/
