site_name: gcxmlib
site_url:
site_author: Ryou Ohsawa
site_description:
  A cross-matching library with great circle.

repo_name: ryou_ohsawa/gcxmlib
repo_url: https://bitbucket.org/ryou_ohsawa/gcxmlib/src/master/
edit_uri: ""

copyright: Copyright &copy; 2021&ndash; Ryou Ohsawa

theme:
  name: 'material'
  icon:
    logo: logo
  language: 'en'
  palette:
    scheme: default
    primary: blue grey
    accent: deep orange
  features:
    - navigation.expand
    - navigation.tabs
    - header.autohide

extra_css:
  - css/local.css
extra_javascript:
  - js/config_mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - toc:
      toc_depth: 3
  - extra
  - admonition
  - smarty
  - sane_lists
  - meta
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: True
  - pymdownx.arithmatex:
      generic: true

nav:
  - Front Page:
    - Top Page: index.md
    - bitbucket: https://bitbucket.org/ryou_ohsawa/gcxmlib/src/master/
    - PyPi: https://pypi.org/project/gcxmlib/
  - Reference:
    - reference/index.md
    - Python:
      - Getting Started: reference/python/index.md
      - direction_cosine: reference/python/direction_cosine.md
      - footprint: reference/python/footprint.md
      - trail: reference/python/trail.md
      - trajectory: reference/python/trajectory.md
      - Index: reference/python/index_table.md
    - C++:
      - Getting Started: reference/cpp/index.md
      - constants: reference/cpp/constants.md
      - angle: reference/cpp/angle.md
      - vector3: reference/cpp/vector3.md
      - matrix3: reference/cpp/matrix3.md
      - direction_cosine: reference/cpp/direction_cosine.md
      - footprint: reference/cpp/footprint.md
      - great_circle: reference/cpp/great_circle.md
      - minor_arc: reference/cpp/minor_arc.md
      - trail: reference/cpp/trail.md
      - trajectory: reference/cpp/trajectory.md
      - functions: reference/cpp/functions.md
      - Index: reference/cpp/index_table.md
      - Source code: reference/cpp/source.md
